### ISSUE TITLE
Board 기능 구현

### ISSUE THREAD

**Issue by bluenight12** [dnd-mentee-3rd/dnd-mentee-3rd-8-traview#23]
- [x] 제목 및 내용 업로드 기능 구현

- [ ] 신기해요 기능 및 별점 (5단계) 기능 구현

- [ ] 마이페이지 내 게시글 삭제 및 수정 기능 구현

- [ ] 게시글 내 댓글 기능 구현

- [ ] 지역 선택 및 분위기 선택 기능 구현

- [ ] 사진 업로드 기능 구현

**Comment by miue22** [comment]
요것도 이슈가 다소 큰 것 같습니다. Epic으로 나누는게 좋을 것 같아요~
