### ISSUE TITLE
Banner, BestPictures 코드 리뷰

### ISSUE THREAD

**Issue by miue22** [dnd-mentee-3rd/dnd-mentee-3rd-8-traview#36]
살짝 둘러보고 있는 중인데요, 그때 그때 간단하게 코드리뷰 이슈 올려보려고 합니다. 
'내가 리뷰해주는대로 바꿔라!'는건 절대 아니구요 ^^;; 자유롭게 의견 교환 되었으면 좋겠습니다!
(근데 Label에 붙어있는 아이콘은 어디서 가져온건가요? ㅋㅋ)

### Banner

https://github.com/dnd-mentee-3rd/dnd-mentee-3rd-8-traview/blob/9b8ac2741479a8c27b3386e82e0b24d791c14596/client/src/components/Banner/Banner.js#L136-L147

props로 일일이 넘겨주기보다는 `data` 자체를 넘기고, 받는 쪽에서 destructuring하면 어떨까요?

```js
const BestPictures = ({ data }) => {
    const {num,interest, like, user, username, imagePath, location} = data;
   
    ...
}

...
<BestPicture data={data} />
...

```

### BestPictures.js

https://github.com/dnd-mentee-3rd/dnd-mentee-3rd-8-traview/blob/9b8ac2741479a8c27b3386e82e0b24d791c14596/client/src/components/Banner/BestPictures.js#L146-L191

props의 상태에 따라 다른 View를 보여줘야 하는 상황 같은데요! 가독성이 조금 더 고려되면 좋을 것 같습니다.
아래와 같은 구조는 어떤가요?
(Props 네이밍도 조금 더 명시적으로 바꾸면 좋을 것 같습니다! 예를 들면 `pictureNo`라던가 ... )

```js
const BestPicture = () => {
    return 윗부분;
}

const Picture = () => {
    return 아랫부분;
}

export default const BestPictures = ({ num }) => {
    const isFirstPicture = num === 0;

    return isFirstPicture ? <BestPicture/> : <Picture />;

}
```

**Comment by HoJin9622** [comment]
감사합니다!
라벨에 붙어있는 아이콘은 윈도우 이모지입니다!
단축어: (윈도우 로고키) + (마침표)
