### ISSUE TITLE
MainArea 코드리뷰

### ISSUE THREAD

**Issue by miue22** [dnd-mentee-3rd/dnd-mentee-3rd-8-traview#37]
### MainArea.js

https://github.com/dnd-mentee-3rd/dnd-mentee-3rd-8-traview/blob/9b8ac2741479a8c27b3386e82e0b24d791c14596/client/src/components/MainArea/MainArea.js#L60-L70

#### 변수 선언의 상수화
`apiRoot`나 `accessKey`는 이 컴포넌트가 아니더라도 여러군데서 사용될 가능성이 있는 것 같은데요, 그렇다면 지역 변수로 선언하기보다는 공통적으로 사용할 수 있는 상수 파일을 따로 만들어서 import하여 사용하는게 좋을 것 같습니다. 그렇게 했을 때 장점은
- 변경사항이 발생하였을 때 일일이 검색할 필요 없이, 해당 상수 파일만 들여다보면 됨
  - 보통은 IDE에서 Find Usage를 지원하기 때문에, 훨씬 보기 편해집니다
- 마찬가지로 일일이 여러군데 수정해줄 필요 없이 한 군데만 수정하면 됨(관리포인트 단일화)
- 여기저기서 각각 정의하여 사용하면 (아무리 copy&paste를 하더라도) 오타가 발생하는 등의 이슈로 인해 특정 부분에서만 에러가 발생할 여지가 있음
- 기타 등등... 지금 생각나는건 이정도네용

따라서 아래와 같은 구조는 어떨지 고려해보세요 :)
```js
// src/const/apiConst.js
export const API_ROOT = 'https://api.unsplash.com'; 
export const ACCESS_KEY = process.env.REACT_APP_ACCESSKEY; 
```
```js
// src/components/MainArea/MainArea.js
import { API_ROOT, ACCESS_KEY  } from '../../../const/apiConst.js'

```

#### 함수 정의
함수를 컴포넌트 내부에서 정의하면 rerender될 때 마다 함수가 새로 정의됩니다. 
물론 함수를 정의하는 것이 리소스를 많이 잡아먹지는 않기 때문에 당장 성능상으로 문제가 되지는 않겠지만요,, 때로는 치명적일수도 있습니다. 

이럴때는 **컴포넌트 바깥에서 함수를 정의하는** 간단한 방법으로 회피할 수 있으니 습관화하면 좋을 것 같아요 :)

> 이런 문제를 해결하기 위해 React에서는  `useCallback`이라는 훅을 제공해주고 있습니다. 나중에 한번 찾아보셔요 ㅎㅎ

```js

const fetchImages = (images, setImages) => {
    const apiRoot = 'https://api.unsplash.com';
    const accessKey = process.env.REACT_APP_ACCESSKEY;
    axios
      .get(`${apiRoot}/photos/random?client_id=${accessKey}&count=15`)
      .then((res) => setImages([...images, ...res.data]));
  };

const MainArea = ( ) => {
    const [images, setImages] = useState([]);

    useEffect(() => {
        fetchImages(images, setImages);
    }, []);


}
```

#### await의 사용

Axios를 이용해 API를 호출할 때 async&await를 사용해보는건 어떨까요? 물론 지금 방식으로도 잘 동작하겠지만, 코드가 좀 더 깔끔해질거에요!

```js
//AS-IS
const fetchImages = () => { 
   const apiRoot = 'https://api.unsplash.com'; 
   const accessKey = process.env.REACT_APP_ACCESSKEY; 
   axios 
     .get(`${apiRoot}/photos/random?client_id=${accessKey}&count=15`) 
     .then((res) => setImages([...images, ...res.data])); 
 }; 


//TO-BE
const fetchImages = async () => {
    const apiRoot = 'https://api.unsplash.com';
    const accessKey = process.env.REACT_APP_ACCESSKEY;    

    const result = await axios.get(`${apiRoot}/photos/random?client_id=${accessKey}&count=15`); 

    setImages([...images, ...result.data]));
};
```

**Comment by miue22** [comment]
@HoJin9622 이 코드 리뷰 내용을 DND 슬랙 자유게시판 채널에 공유해도 괜찮을까요? 🤔 
(코드 원작자의 의견을 ㅎㅎ)

**Comment by HoJin9622** [comment]
넵 괜찮습니다!
